[puppet_generate_detailed_report]
python.version = python3
python.required = 3.13
description = Generates a puppet:detailed event from a puppet:summary event
label = Generate detailed Puppet report
is_custom = 1
payload_format = json
icon_path = alert_puppet_generate_detailed_report.png

[puppet_run_task]
python.version = python3
python.required = 3.13
description = Run a Puppet Task on the events host with Puppet Enterprise
label = Run a Puppet Task
is_custom = 1
payload_format = json
icon_path = alert_puppet_run_task.png
param.action_target = $result.host$
param.puppet_environment = production

[puppet_run_plan]
python.version = python3
python.required = 3.13
maxtime = 1h
description = Run a Puppet Plan with Puppet Enterprise
label = Run a Puppet Plan
is_custom = 1
payload_format = json
icon_path = alert_puppet_run_task.png
param.puppet_environment = production
