[id]
name = TA-puppet-alert-orchestrator
version = 2.0.0

[install]
state_change_requires_restart = true
is_configured = false
state = enabled
build = 1

[launcher]
author = Puppet, Inc.
version = 2.0.0
description = Collection of alert actions specifically for Puppet Enterprise.

[ui]
is_visible = 1
label = Puppet Alert Orchestrator
docs_section_override = AddOns:released

[package]
id = TA-puppet-alert-orchestrator

[triggers]
reload.addon_builder = simple
reload.ta_puppet_alert_actions_account = simple
reload.ta_puppet_alert_actions_settings = simple
reload.passwords = simple