[script://$SPLUNK_HOME/etc/apps/TA-puppet-alert-orchestrator/bin/inputs/orchestrator_actions.py]
disabled = 0
interval = 3600
passAuth = splunk-system-user
python.version = python3
python.required = 3.13
