name: Package Splunk App

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Version ID
        id: version-tag
        run: echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python build dependencies
        run: pip install -r requirements-dev.txt

      - name: Install Python runtime dependencies into lib/
        run: pip install -r requirements.txt --target TA-puppet-alert-orchestrator/lib

      - name: Build configuration page (UCC)
        run: ucc-gen build --source TA-puppet-alert-orchestrator

      - name: Package app
        run: slim package output/TA-puppet-alert-orchestrator

      - name: Upload App Build
        uses: actions/upload-artifact@v4
        with:
          name: TA-puppet-alert-orchestrator-${{ steps.version-tag.outputs.version }}
          path: TA-puppet-alert-orchestrator-*.tar.gz
